name: Build Multiple Services

on:
  push:
    branches:
      - main
      - dev
      - BK3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: notification, dir: PRH_NotificationService }
          - { name: user, dir: PRH_UserService }
          - { name: report, dir: PRH_ReportService }
          - { name: quiz, dir: PRH_QuizService }
          - { name: group, dir: PRH_GroupService }
          - { name: payment, dir: PRH_PaymentService }
          - { name: chat, dir: PRH_ChatService }
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Build ${{ matrix.service.name }} Service
      working-directory: ./${{ matrix.service.dir }}
      run: dotnet build --configuration Release

    - name: Publish ${{ matrix.service.name }} Service
      working-directory: ./${{ matrix.service.dir }}
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload ${{ matrix.service.name }} Service artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.service.name }}-service-publish
        path: ./${{ matrix.service.dir }}/publish

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image for ${{ matrix.service.name }} Service
      working-directory: ./${{ matrix.service.dir }}
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.name }}-service:latest -f Dockerfile .

    - name: List Docker images
      run: docker images

    - name: Push Docker image for ${{ matrix.service.name }} Service to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.name }}-service:latest
